baseurl = "https://andalibmalit.github.io"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Andalib Samandari's website"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Research"
url = "/research/"
weight = 1
[[menu.main]]
name = "Resume"
url = "/resume/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[params]
custom_css = ["css/theme-override.css"]
description = "AI researcher focusing on reinforcement learning and AI ethics."
githubURL = "https://github.com/andalibmalit"
linkedinURL = "https://linkedin.com/in/andalibsamandari"
email = "andalibmalit@gmail.com"
footer = "[<img src=\"/images/github.svg\" style=\"width:25px;height:25px;\">](https://github.com/andalibmalit)[<img src=\"/images/gmail.svg\" style=\"width:25px;height:25px;\">](mailto:andalibmalit@gmail.com)[<img src=\"/images/X_logo_2023.svg\" style=\"width:25px;height:25px;\">](https://x.com/)[<img src=\"/images/Linkedin_icon.svg\" style=\"width:25px;height:25px;\">](https://linkedin.com/in/andalibsamandari)"

[params.seo]
description = "AI researcher website"